server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
  rabbitmq:
    host: lix3-rabbitmqservice.caas.haihangyun.cn
    port: 30988
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true