server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: microservice-auth-server
  #数据库配置
  data:
    mongodb:
      uri: mongodb://root:adminpwd@host:port/auth_server
  # redis设置
  redis:
      database: 0 # Redis数据库索引（默认为0）
      host:  # Redis服务器地址
      port:  # Redis服务器连接端口
      # password:  # Redis服务器连接密码（默认为空）
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 0 # 连接超时时间（毫秒）

#安全配置
security:
  #oauth2配置
  oauth2:
    resource:
      filter-order: 3