server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeeAllencn/spring-cloud-config-repo.git      # 配置Git仓库的地址
          username: LeeAllencn                                                        # Git仓库的账号
          password: King.13                                                        # Git仓库的密码
encrypt:
  keyStore:
    location: classpath:/server.jks # jks文件的路径
    password: letmein               # storepass
    alias: mytestkey                # alias
    secret: changeme                # keypass